name: arithmetic_amallar
description: This package helps to solve arithmetic problems easily!
version: 1.0.0
repository: https://github.com/Bexruzbek-dev/arithmetic_amallar
homepage: https://github.com/Bexruzbek-dev/arithmetic_amallar

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

